name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  docker-build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        target: frontend
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        target: backend
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          API_TOKEN=${{ secrets.API_TOKEN }}

    - name: Verify Deployment
      run: |
        echo "Frontend image pushed to:"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend@sha256:$(docker manifest inspect -v ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest | jq -r '.Descriptor.digest')"
        echo "Backend image pushed to:"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend@sha256:$(docker manifest inspect -v ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest | jq -r '.Descriptor.digest')"
